//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lojistik_Projesi__11Nisan2019
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ürünler> ÜrünlerSet { get; set; }
        public virtual DbSet<Departman> DepartmanSet { get; set; }
        public virtual DbSet<Personel> PersonelSet { get; set; }
        public virtual DbSet<TaşıyıcıFirma> TaşıyıcıFirmaSet { get; set; }
        public virtual DbSet<ÜreticiFirma> ÜreticiFirmaSet { get; set; }
        public virtual DbSet<Sevkiyat> SevkiyatSet { get; set; }
        public virtual DbSet<AlıcıFirma> AlıcıFirmaSet { get; set; }
        public virtual DbSet<Firmalar> FirmalarSet { get; set; }
    }
}
