//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lojistik_Projesi__11Nisan2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int PersonelID { get; set; }
        public string PersonlAdı { get; set; }
        public string PersonelSoyadı { get; set; }
        public int Telefon { get; set; }
        public string Adres { get; set; }
        public int DepartmanDeparmanID { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
